### ISSUE TITLE
How do we view liked songs?

### ISSUE THREAD

**Issue by Void48** [williamckha/spicetify-fluent#10]

**Comment by wian-lloyd** [comment]
You can go to library and liked songs from there. 👀
![image](https://user-images.githubusercontent.com/48918125/135586105-56b39ad5-0886-42cd-a51e-492da4696cfa.png)

**Comment by Void48** [comment]
> You can go to library and liked songs from there. 👀 ![image](https://user-images.githubusercontent.com/48918125/135586105-56b39ad5-0886-42cd-a51e-492da4696cfa.png)

Don't have it on my japanese spotify account but I have it on other one

**Comment by Void48** [comment]
@wian-lloyd ok so when you don't have any playlists it doesn't show **Liked Songs** should fix that if possible 👍🏻 
![2xs5YCOBhg](https://user-images.githubusercontent.com/85196642/135760690-ccf76a36-6142-4e25-a62a-9059b489eca4.gif)
