### ISSUE TITLE
Offcenter Icons

### ISSUE THREAD

**Issue by kneekoh** [williamckha/spicetify-fluent#15]
Latest version of Spotify, Spicetify, and Fluent. Tried Uninstalling and Reinstalling about 3 times and every time the icons were offcenter.
![Screenshot 2021-10-29 163342](https://user-images.githubusercontent.com/35415820/139511520-d4306dcc-dd1f-41d8-b050-c728e62d3dba.png)

**Comment by Nekorystar** [comment]
same problem here

**Comment by ItsCer0** [comment]
same

**Comment by fukwho** [comment]
Same problem!

**Comment by rlaphoenix** [comment]
I still have this problem.
