### ISSUE TITLE
Fluent theme is broken

### ISSUE THREAD

**Issue by LuckeeDev** [williamckha/spicetify-fluent#17]
## Computer info
Spotify version: 1.71.560.gc21c3367
Spicetify version: 2.7.1

## Issue
Play and track control buttons don't work, alongside other pieces of UI that seem to be broken.

## Screenshot
![IMG-20211101-WA0039.jpg](https://user-images.githubusercontent.com/61506420/139685786-3131046f-9dcf-40be-95d1-211ded4453ef.jpg)

**Comment by williamckha** [comment]
Did you follow all the installation instructions? Looks like fluent.js might not be installed

**Comment by bonnko** [comment]
I have the same issue, I tried to reinstalled the theme and followed the steps again, but it still doesn't work.

**Comment by LuckeeDev** [comment]
> Did you follow all the installation instructions? Looks like fluent.js might not be installed

It seems like I hadn't installed it properly. After a clean install, it works perfectly. Thanks!
