### ISSUE TITLE
Various CSS no longer functioning in latest Spotify release

### ISSUE THREAD

**Issue by rlaphoenix** [williamckha/spicetify-fluent#20]
![image](https://user-images.githubusercontent.com/17136956/146371629-b1dadd8f-2dd8-4cc7-b5a8-3e327126df45.png)

As you can see the sidebar has various issues, the top bar's back/forward is messed up.

There are possibly other issues but that's what I've noticed.

**Comment by rlaphoenix** [comment]
[Latest master as of now](https://github.com/williamckha/spicetify-fluent/commit/4e02067268b1c876f4f3e5df49d0448ded663227) seems to work fine if you downgrade Spotify to `v1.1.72.439`.

**Comment by heitormvl** [comment]
Where do I find Spotify v1.1.72.439? Mine's v1.1.74.631 and I'm having the same problem as @rlaphoenix

**Comment by rlaphoenix** [comment]
> Where do I find Spotify v1.1.72.439? Mine's v1.1.74.631 and I'm having the same problem

https://spotify.en.uptodown.com/windows/download/4110693

**Comment by rlaphoenix** [comment]
Closing this as the majority of issues brought up are either fixed, already known, or have differed since.
