### ISSUE TITLE
New Update, destroyed image

### ISSUE THREAD

**Issue by qeinz** [williamckha/spicetify-fluent#21]
Hello,

Since the new Spotify update, unfortunately, the whole UI is bugged again.

**Comment by youngerstar** [comment]
Yes, for example, the cover of playlist seems strange. https://github.com/morpheusthewhite/spicetify-themes/issues/648
![image](https://user-images.githubusercontent.com/46211595/146768144-6e891084-c27a-43d9-81aa-3befc6ab079c.png)

**Comment by rlaphoenix** [comment]
This is fixed as of commit https://github.com/williamckha/spicetify-fluent/commit/5d299510c7de2dcc553f79ffbc1730a09f2aadcf
