### ISSUE TITLE
Home, Search, Library Icons Misaligned After The Theme Is Applied

### ISSUE THREAD

**Issue by EpicBProgrammingOnReddit** [williamckha/spicetify-fluent#22]
I Have A Problem Here... After These Failed Tries, I Got It Working Again But Those Icons Like Home, Search, & Library Are Misaligned. Is There A Way To Fix It?
<img width="61" alt="image" src="https://user-images.githubusercontent.com/89497362/147375364-0ad2b32b-6a89-43cf-9430-458f31285ccb.png">

**Comment by altuser999** [comment]
I have the same problem, even after adding 
`[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,`
to the config-xpui.ini file. I also can't resize the sidebar. Any fixes yet?

**Comment by Melodi17** [comment]
I'm having the same problem, can the devs please get around to fixing this soon

**Comment by AndresD172** [comment]
I have the same problem on Fedora Linux, was anyone able to fix this problem?

**Comment by AndresD172** [comment]
also, the play button is not displayed correctly and the magnifying glass symbol is overlapping the text in the search bar
![2022-02-15-153502_275x222_scrot](https://user-images.githubusercontent.com/57467120/154155974-f3e08bfd-0751-490a-a52a-9704393bfa08.png)
![2022-02-15-153446_367x45_scrot](https://user-images.githubusercontent.com/57467120/154155980-c61281b5-dff8-489f-99a9-a6795df8e5f9.png)

**Comment by AndresD172** [comment]
Oh, I see. So, I'm going to do the play button issue!

**Comment by AndresD172** [comment]
Hey bro @rlaphoenix! Miraculously the play button is working correctly after updating the theme. thanks for helping me!

**Comment by rlaphoenix** [comment]
This is fixed as of https://github.com/williamckha/spicetify-fluent/commit/5d299510c7de2dcc553f79ffbc1730a09f2aadcf

**Comment by decipher3114** [comment]
I am getting this issue, 
![image](https://user-images.githubusercontent.com/84389932/190469581-c4cf21bd-3cec-41bd-a3eb-ce56dfa30d7c.png)
