### ISSUE TITLE
Is the sidebar resizable?

### ISSUE THREAD

**Issue by AfiaAly** [williamckha/spicetify-fluent#24]
Not sure if this is where I can post such a question, so apologies if I'm in the wrong place. I was wondering if any of the sidebars are sizable (normal sidebar and friends activity). If not, is there a way I can get the name of the playlist that's in the sidebar? It would be nice, since when I don't know what the playlist cover looks like, I need to click each one to find the one I'm looking for.

**Comment by rlaphoenix** [comment]
It's not at the moment no. It's specifically disabled from being resized. Even if you could resize it, that text wouldn't actually be there.

**Comment by rlaphoenix** [comment]
I'm closing this issue due to the more question nature of this issue. I've opened https://github.com/williamckha/spicetify-fluent/issues/44 which may appease what this issue ultimately asks, if not, feel free to open a new more specific issue.
