### ISSUE TITLE
Add this repo to the spicetify marketplace

### ISSUE THREAD

**Issue by Salaron** [williamckha/spicetify-fluent#47]
Fluent theme is available in spicetify marketplace from [this repo](https://github.com/morpheusthewhite/spicetify-themes). But the theme is not updated to current state and have some glitches.
If this repo will be added to marketplace, users can get latest fixes faster.

_Sorry for my English._

**Comment by rlaphoenix** [comment]
![image](https://user-images.githubusercontent.com/17136956/155762574-12ed739d-f7f7-4b89-ad74-804c1e21337a.png)

It's now available on the Spicetify Marketplace.
