### ISSUE TITLE
xpui.js not found

### ISSUE THREAD

**Issue by MayonnaiseTheInstrument** [williamckha/spicetify-fluent#53]
in powershell, in the patching section:
xpui.js not found

I can find config-xpui.ini but I don't know what to do with the xpui.js
Also some things are duplicated in the UI
![image](https://user-images.githubusercontent.com/62947066/155982475-38ad4dc4-a83c-49aa-9c39-117b794a12e5.png)

**Comment by rlaphoenix** [comment]
What version of Spotify are you on, and if you're on an old version (<1.1.78.x) can you try update to v1.1.79.x while also making sure you update to spicetify v2.9.1 or newer?

What do you mean by xpui.js not found? Could you show us the installation log?

**Comment by rlaphoenix** [comment]
Marking this as stale as there has been no updates for 21 days now.

**Comment by rlaphoenix** [comment]
Closing as this has been stale and awaiting a response for 6 weeks now.

**Comment by Jnss98b** [comment]
@rlaphoenix not op but I have the same issue

spicetify v2.9.8
Spotify for Windows
1.1.84.716.gc5f8b819

![image](https://user-images.githubusercontent.com/24306400/167560612-63e5184d-079e-4d53-8d42-e05b02bd97cd.png)

**Comment by Jnss98b** [comment]
Ok I found the solution. It was bc of windows store spotify. Downloading spotify from their website and it should be good
