### ISSUE TITLE
theme not working properly

### ISSUE THREAD

**Issue by Basic6969** [williamckha/spicetify-fluent#54]
![image](https://user-images.githubusercontent.com/98833613/156230728-c4bf202c-68f0-41b1-a87d-e7dd5762e1db.png)
any fixes?

**Comment by williamckha** [comment]
fluent.js is likely properly installed because the sidebar navigation icons have the accent divs (which are inserted by the JS extension)

Ensure that you are using the latest version of spicetify (run `spicetify upgrade` in console)

**Comment by Basic6969** [comment]
> fluent.js is likely properly installed because the sidebar navigation icons have the accent divs (which are inserted by the JS extension)
> 
> Ensure that you are using the latest version of spicetify (run `spicetify upgrade` in console)

yes its the latest version

**Comment by Basic6969** [comment]
any fixes?

**Comment by Basic6969** [comment]
its working now
