### ISSUE TITLE
Remake dark mode

### ISSUE THREAD

**Issue by bathtimethiago** [williamckha/spicetify-fluent#56]
https://1drv.ms/u/s!AiGYPzCg7KuggcxouaDm3DqznQZfig

Drag on C:\Users\YouUserFolder\\.spicetify\Themes\Fluent and replace

**Comment by bathtimethiago** [comment]
What?

**Comment by bathtimethiago** [comment]
I dont know do that

**Comment by rlaphoenix** [comment]
Hi, yes, it would be much better as a pull request. I am closing this as you have made a separate issue for the same thing and I have replied to you there with instructions and information. https://github.com/williamckha/spicetify-fluent/issues/58
