### ISSUE TITLE
sidebar playlist covers bug

### ISSUE THREAD

**Issue by alexanderpwnz** [williamckha/spicetify-fluent#6]
hello, the images don't fit/shrink in the sidebar.
![image](https://user-images.githubusercontent.com/46689694/134169996-baba344c-fd70-401d-8549-686e032e7892.png)

spicetify version: 2.6.4
spotify version: 1.1.68.628

how can i fix this?

**Comment by BearTS** [comment]
I am getting it too

**Comment by wian-lloyd** [comment]
I think I've had this issue!
What extensions do you have loaded for Spicetify?

Powershell:
```
cd "$(spicetify -c | Split-Path)";
explorer .;
```

File `config-xpui.ini`
```
[AdditionalOptions]
extensions     = fluent.js
```

Mine had dribblish.js also loaded, removing and re-applying fixed for me.

**Comment by BearTS** [comment]
Oh yeah, Thanks a lot . I had fluent.js missing and also dribblish.js also being loaded which is the culprit 
Thanks

**Comment by BearTS** [comment]
Also I have another issue
![image](https://user-images.githubusercontent.com/65192718/135258875-a081f2a3-32ac-4ccc-ab45-4f726003a9e2.png)
a lot of them doesn't load

**Comment by wian-lloyd** [comment]
> Also I have another issue ![image](https://user-images.githubusercontent.com/65192718/135258875-a081f2a3-32ac-4ccc-ab45-4f726003a9e2.png) a lot of them doesn't load

Interesting... Can you see this flyout option for "Developer Tools"? I'm thinking maybe we can check the logs for errors.

![image](https://user-images.githubusercontent.com/48918125/135261445-5eca6aed-286e-43e4-8c19-8a475c7f01e4.png)

**Comment by williamckha** [comment]
Latest commit 91c03a6 should fix this issue
Ensure that these two lines are added to the Patch section of your config-xpui.ini file:
```ini
[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,
```
