### ISSUE TITLE
It´s completly buggy

### ISSUE THREAD

**Issue by SkyKingPX** [williamckha/spicetify-fluent#79]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.0.1165.gabf054ab
- Spicetify version: Spicetify v2.14.3
- Fluent installation method: Spicetify Marketplace
```

### 📝 Description

Install the theme

### 📸 Screenshots

How it looks:
![211582666-8f833b0e-acb8-4edf-b0bd-e6f65b98481f](https://user-images.githubusercontent.com/95442431/211584002-d91dd264-12c2-45fb-8f2c-bd930decb53c.png)

My installed Extensions/...:
![image](https://user-images.githubusercontent.com/95442431/211583002-3f1e22d9-8d64-4677-99e5-895a8821ba74.png)
![image](https://user-images.githubusercontent.com/95442431/211583042-3422ac62-dbf6-4cf7-8167-58db8ad2851a.png)

**Comment by marharols** [comment]
Pretty certain spicetify is a bit broken rn, same issue on dribbblish

**Comment by SnowPowerCore** [comment]
Just in case this theme is abandoned by author: there's a developer @christosk92, which is developing Spotify client https://github.com/christosk92/Eum.Windows. This is for those, who really want to have Fluent UI theme.

**Comment by SkyKingPX** [comment]
Ok, i will then close it.
